language: java
jdk:
- openjdk8
script:
- "./gradlew build"
deploy:
  provider: s3
  access_key_id:
    secure: MYmBDPQy2lkEvALHDCm4iolokg+eF4ftLlXZYAlBBQn1GCRIw1ukgUm+/G99OWm6e4Snd5t+jyXVTd0IEs+wmNF+A0qz0T74iGJK9RfIPGApTmXrTHimeNKGFi9tKcgMVEkhXqZsr4esfGUqLiIdpApzMFzYEY9klMSs0t5Kkw5L3ynAOiH1ScoW3vjUjfzZvXadpMgObChNufA2mH4aciZs+ZP7uglSEdmdc3+sk3lwc51jxKeZHi8MH6ziUdaeF159sYxGhufRzywfNcLDUU+0ctAm906yOxcHK6OnaX1r91XTrEmW4grB3bzFOgwWQVm5bc4sG0EcjM2UXFtqTeJnM/vLhnU3YeNWcgWkoju3znLHICI3TokYRRUA+GAjp4E4R2jmuQGeTu8sASVHqtf9kOknLLgsR26TZvXazgvYCGLQ9CJid5V/AH0MpN4/8728jyn2Ncnxv1YrDaetAh5xoVHpXWlTwv0MyXa5JI8MD6bTZA6FzvcyfFn2RcSRbEbkxKFYuPbS7N5NiVbIJOIsWDZfZhcpYDApAryCJV1/4TjWOeC3mh9v2nqkOdlvdSrRaxo18TzTKxrSTlAWEDTGk+zMie/TdRNu/BJt6BvHHmXLjE4t1sWI/EamwDZ4DAvgKR04DZgyDirxBAMon6U2utEPGguOoo/qdUSPNUw=
  secret_access_key:
    secure: JXYpIDVPODTkurc5aWACAGe8hwkuwXehRsXnpYRhxXnxxvm/LKFmgdaNDwzaPJ3oMqL8mJL+7qwhkJ6pJUx7C/9gfZNkOxJkE8ZlBIc75AONkgcKv2OJ+J5VKrhqoIR9+IFp0kihzi29Tc04JkUKjL44iaXNejFoQDSeFW0VMUM/OBFsa2EfZYHZzCPcOwdoCCtfhoL1j1TEQ33XRmQykrji1PJm8mv2xbLrPrgkfgb1iXy152UONtn56mikjQt9rbjoe0Mn8/5nAyiFZ3xKGLzOt/YJtxUCJfnqEZdwXtxiCLRER0pGMlcprUsQxvLFZC65VkT35UNqECMKUFtj+fBkTOBATmad2vVN0MP8x2UOokqebjpXGnDHmPAklum2xuPz3EOYsdqNvIV9gaZY7m/egvKC/HH/0a7VkAVTHd0CzXXmhC2wqHgQ2tgZJe3Lrem4UCfT6tkszFqQF9btAzfc8fIPBjlKX0SGNNkitxy3NU612LxKKSOyDjagZKxbbkqJLwxtXPYTXSpmLd1edvm+MkYPlRkPtZpDBPDcstHnIr/9T+AU1lT1Fgm+1rg0vTQdSp07YWW39QgLg+xqK1GMI83HrFiZUskfZkg9rZwUTKaLJTcOnFwgeG59UTkNssjtvCKxwvYBMEtgd3YBrOnqYgh0l7BDqvegolTXOY4=
  bucket: S3 Bucket
  skip_cleanup: true
